In [36]:
pip install gdown==v4.6.3

In [37]:
!gdown 1La5PlbYWPH1VyiE8Zq2BDAYWqtpd56Z2

Downloading...
From: https://drive.google.com/uc?id=1La5PlbYWPH1VyiE8Zq2BDAYWqtpd56Z2
To: /content/Expanded_data_with_more_features.csv
100% 2.91M/2.91M [00:00<00:00, 149MB/s]


In [38]:
import pandas as pd
data = pd.read_csv('/content/Expanded_data_with_more_features.csv')

In [39]:
data

Unnamed: 0  Gender EthnicGroup          ParentEduc     LunchType  \
0               0  female         NaN   bachelor's degree      standard   
1               1  female     group C        some college      standard   
2               2  female     group B     master's degree      standard   
3               3    male     group A  associate's degree  free/reduced   
4               4    male     group C        some college      standard   
...           ...     ...         ...                 ...           ...   
30636         816  female     group D         high school      standard   
30637         890    male     group E         high school      standard   
30638         911  female         NaN         high school  free/reduced   
30639         934  female     group D  associate's degree      standard   
30640         960    male     group B        some college      standard   

        TestPrep ParentMaritalStatus PracticeSport IsFirstChild  NrSiblings  \
0           none             married     regularly          yes         3.0   
1            NaN             married     sometimes          yes         0.0   
2           none              single     sometimes          yes         4.0   
3           none             married         never           no         1.0   
4           none             married     sometimes          yes         0.0   
...          ...                 ...           ...          ...         ...   
30636       none              single     sometimes           no         2.0   
30637       none              single     regularly           no         1.0   
30638  completed             married     sometimes           no         1.0   
30639  completed             married     regularly           no         3.0   
30640       none             married         never           no         1.0   

      TransportMeans WklyStudyHours  MathScore  ReadingScore  WritingScore  
0         school_bus            < 5         71            71            74  
1                NaN         5 - 10         69            90            88  
2         school_bus            < 5         87            93            91  
3                NaN         5 - 10         45            56            42  
4         school_bus         5 - 10         76            78            75  
...              ...            ...        ...           ...           ...  
30636     school_bus         5 - 10         59            61            65  
30637        private         5 - 10         58            53            51  
30638        private         5 - 10         61            70            67  
30639     school_bus         5 - 10         82            90            93  
30640     school_bus         5 - 10         64            60            58  

[30641 rows x 15 columns]

For the categorical missing values
- find unique values
- find mode (most frequent)
- impute nan with mode value

--> TransportMeans, PracticeSport, ParentMaritalStatus, TestPrep, LunchType, ParentEduc, EthincGroup

In [40]:
data.isnull().sum()

Unnamed: 0                0
Gender                    0
EthnicGroup            1840
ParentEduc             1845
LunchType                 0
TestPrep               1830
ParentMaritalStatus    1190
PracticeSport           631
IsFirstChild            904
NrSiblings             1572
TransportMeans         3134
WklyStudyHours          955
MathScore                 0
ReadingScore              0
WritingScore              0
dtype: int64

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           30641 non-null  int64  
 1   Gender               30641 non-null  object 
 2   EthnicGroup          28801 non-null  object 
 3   ParentEduc           28796 non-null  object 
 4   LunchType            30641 non-null  object 
 5   TestPrep             28811 non-null  object 
 6   ParentMaritalStatus  29451 non-null  object 
 7   PracticeSport        30010 non-null  object 
 8   IsFirstChild         29737 non-null  object 
 9   NrSiblings           29069 non-null  float64
 10  TransportMeans       27507 non-null  object 
 11  WklyStudyHours       29686 non-null  object 
 12  MathScore            30641 non-null  int64  
 13  ReadingScore         30641 non-null  int64  
 14  WritingScore         30641 non-null  int64  
dtypes: float64(1), int64(4), object(10)


In [42]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [43]:
import pandas as pd
from scipy.stats import chi2_contingency

# Assuming 'data' is your DataFrame
contingency_table = pd.crosstab(data.isnull().any(axis=1), data.isnull().any(axis=1))

chi2, p, _, _ = chi2_contingency(contingency_table)

print(f"Chi-square value: {chi2}")
print(f"P-value: {p}")

# Interpret the results
if p < 0.05:
    print("There is a significant relationship between the missingness of variables in the dataset.")
else:
    print("There is no significant relationship between the missingness of variables in the dataset.")


Chi-square value: 30636.719551571325
P-value: 0.0
There is a significant relationship between the missingness of variables in the dataset.


Check the unique values

In [44]:
data['EthnicGroup'].unique()

array([nan, 'group C', 'group B', 'group A', 'group D', 'group E'],
      dtype=object)

In [45]:
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import OneHotEncoder

# Assuming 'data' is your DataFrame and 'categorical_column' is the column to process
categorical_mapping = {'group A': 1, 'group B': 2, 'group C': 3, 'group D': 4, 'group E': 5}

# Step 1: Encode categorical values to corresponding numbers
data['EthnicGroup'] = data['EthnicGroup'].map(categorical_mapping)

In [46]:
data['EthnicGroup'].unique()

array([nan,  3.,  2.,  1.,  4.,  5.])

In [47]:
# TransportMeans, PracticeSport, ParentMaritalStatus, TestPrep, LunchType, ParentEduc

In [48]:
data['ParentEduc'].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school', nan],
      dtype=object)

In [49]:
# Assuming 'data' is your DataFrame and 'EthnicGroup' is the column to process
categorical_mapping = {'high school': 1, 'some high school': 2, "bachelor's degree": 3, "master's degree": 4, "associate's degree": 5}

# Step 1: Encode categorical values to corresponding numbers
data['ParentEduc'] = data['ParentEduc'].map(categorical_mapping)

In [50]:
data['LunchType'].unique()

array(['standard', 'free/reduced'], dtype=object)

In [51]:
# Assuming 'data' is your DataFrame and 'EthnicGroup' is the column to process
categorical_mapping = {'standard': 1,  'free/reduced': 2}

# Step 1: Encode categorical values to corresponding numbers
data['LunchType'] = data['LunchType'].map(categorical_mapping)

In [52]:
data['TestPrep'].unique()

array(['none', nan, 'completed'], dtype=object)

In [53]:
# Assuming 'data' is your DataFrame and 'EthnicGroup' is the column to process
categorical_mapping = {'none': 1, 'completed': 2}

# Step 1: Encode categorical values to corresponding numbers
data['TestPrep'] = data['TestPrep'].map(categorical_mapping)

In [54]:
# ParentMaritalStatus
data['ParentMaritalStatus'].unique()

array(['married', 'single', 'widowed', nan, 'divorced'], dtype=object)

In [55]:
# Assuming 'data' is your DataFrame and 'EthnicGroup' is the column to process
categorical_mapping = {'married': 1, 'single': 2,'widowed':3,  'divorced':4 }

# Step 1: Encode categorical values to corresponding numbers
data['ParentMaritalStatus'] = data['ParentMaritalStatus'].map(categorical_mapping)

In [56]:
# PracticeSport
data['PracticeSport'].unique()

array(['regularly', 'sometimes', 'never', nan], dtype=object)

In [57]:
# Assuming 'data' is your DataFrame and 'EthnicGroup' is the column to process
categorical_mapping = {'regularly': 1, 'sometimes': 2,'never':3}

# Step 1: Encode categorical values to corresponding numbers
data['PracticeSport'] = data['PracticeSport'].map(categorical_mapping)

In [58]:
# TransportMeans
data['TransportMeans'].unique()

array(['school_bus', nan, 'private'], dtype=object)

In [66]:
# Assuming 'data' is your DataFrame and 'EthnicGroup' is the column to process
categorical_mapping = {'school_bus': 1, 'private': 2}

# Step 1: Encode categorical values to corresponding numbers
data['TransportMeans'] = data['TransportMeans'].map(categorical_mapping)

In [67]:
data['TransportMeans'].unique()

array([ 1., nan,  2.])

In [60]:
data = data.drop(columns='Unnamed: 0', axis=0)

In [61]:
data.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

In [62]:
columns_to_impute = ['EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport','TransportMeans']

In [63]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import seaborn as sns
import matplotlib.pyplot as plt

In [64]:
imputer = IterativeImputer()

In [71]:
# data[['EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep','ParentMaritalStatus', 'PracticeSport','TransportMeans']] = imputer.fit_transform(data[['EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep', 'ParentMaritalStatus', 'PracticeSport','TransportMeans']])

In [73]:
data.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Gender               30641 non-null  object 
 1   EthnicGroup          28801 non-null  float64
 2   ParentEduc           22163 non-null  float64
 3   LunchType            30641 non-null  int64  
 4   TestPrep             28811 non-null  float64
 5   ParentMaritalStatus  0 non-null      float64
 6   PracticeSport        30010 non-null  float64
 7   IsFirstChild         29737 non-null  object 
 8   NrSiblings           29069 non-null  float64
 9   TransportMeans       27507 non-null  float64
 10  WklyStudyHours       29686 non-null  object 
 11  MathScore            30641 non-null  int64  
 12  ReadingScore         30641 non-null  int64  
 13  WritingScore         30641 non-null  int64  
dtypes: float64(7), int64(4), object(3)
memory usage: 3.3+ MB


In [74]:
# Assuming 'data' is your DataFrame and 'EthnicGroup', 'ParentEduc', etc., are the columns to process
columns_to_impute = ['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore']

# Step 2: Use KNN algorithm to fill missing values
imputed_data = imputer.fit_transform(data[columns_to_impute])

# Convert the imputed data back to a DataFrame with the original column names
imputed_df = pd.DataFrame(imputed_data, columns=columns_to_impute)

# Update the original DataFrame with the imputed values
data[columns_to_impute] = imputed_df


ValueError: could not convert string to float: 'female'